### ISSUE TITLE
Slider onChange is never called when interacting with slider

### ISSUE THREAD

**Issue by aaptho** [ReactUnity/material#1]
Using the **ReactUnity/full-sample** project, if I add an onChange handler to the Slider in `pages/material/index.tsx:127`, this console message never appears

`<Slider onChange={(value) => console.log("Slider onChange value = “ + value)} allowScroll direction="horizontal" mode="normal" max={100} step={20}>{(val) => val * val}</Slider>`

The same issue happens in my own project when using this component.

**Comment by gkurt** [comment]
Should be solved in 0.9.1

**Comment by aaptho** [comment]
Confirmed as fixed in 0.9.1!
